### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by therustydev** [rm-hull/k8055#8]
On new linux distributions, the python command now points to python 3 instead of python 2. The makefile and scripts fail because of this issue. Are there any plans to port the scripts and makefiles to python 3 or to at least change the command to python2 instead?
Personally, I changed the python commands to python2 to make it work, I could send in a PR if need be and also add some documentation to address the issue

**Comment by rm-hull** [comment]
Seems like a good idea to support python 3 since 2.7 will be sunset before long. I'll look into it, unless you fancy crafting a PR upgrading it to python 3?

**Comment by therustydev** [comment]
I will work on it
